### ISSUE TITLE
how to use codesandbox

### ISSUE THREAD

**Issue by JadeDruid** [zicodeng/docz-theme-ztopia#4]
hi,,i want konw if i want to use the codesandbox in this theme?i can't find where to set it

**Comment by zicodeng** [comment]
Hi @JadeDruid, codesandbox is currently not supported by this theme. Let me know if this feature is crucial to you

**Comment by JadeDruid** [comment]
@zicodeng Seriously, I love this theme!But the copy/codesandbox function at work used very commonly, and such like Antd UI library also has a these function.

**Comment by zicodeng** [comment]
@JadeDruid Thanks! I will consider adding this feature over the weekend

**Comment by JadeDruid** [comment]
@zicodeng I'm looking forward to it!Thanks!

**Comment by zicodeng** [comment]
@JadeDruid Hey, I have added CodeSandbox support. You can enable it in in your `doczrc.js` like this:

```
export default {
  ...
  codeSandbox: true,
  ...
}
```

It may not work with complicated demo because the way how Docz core builds the CodeSandbox url. Let me know if it works for you :)

**Comment by JadeDruid** [comment]
@zicodeng I'm sorry to reply you so late
yeah,it worked for me! Thanks :)
have a good day

**Comment by zicodeng** [comment]
@JadeDruid np, happy to help!
